language: ruby

notifications:
  email:
    recipients:  
      - kou@clear-code.com
      - ongaeshi0621@gmail.com
      
rvm:
  # - 1.8.7
  - 1.9.3

before_install:
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh